// <auto-generated />
using System;
using Clothy.CatalogService.DAL.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clothy.CatalogService.DAL.Migrations
{
    [DbContext(typeof(ClothyCatalogDbContext))]
    [Migration("20260119153248_AddSlugInSizesAndTags")]
    partial class AddSlugInSizesAndTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.ClothingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ClothingTypes");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("hexcode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HexCode")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("colors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Color_HexCode", "\"hexcode\" ~ '^#[0-9A-Fa-f]{6}$'");
                        });
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("sizes", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Clothe.ClotheItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClothingTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ClothingTypeId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("clothe_items", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Clothe.ClotheMaterial", b =>
                {
                    b.Property<Guid>("ClotheId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer")
                        .HasColumnName("percentage");

                    b.HasKey("ClotheId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("clothe_materials", null, t =>
                        {
                            t.HasCheckConstraint("ck_clothe_materials_percetage_valid", "\"percentage\" >= 0 AND \"percentage\" <= 100");
                        });
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Clothe.ClothePopularity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClotheId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoldCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClotheId")
                        .IsUnique();

                    b.ToTable("clothe_popularity", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Clothe.ClotheTag", b =>
                {
                    b.Property<Guid>("ClotheId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ClotheId", "TagId");

                    b.HasIndex("ClotheId");

                    b.HasIndex("TagId");

                    b.ToTable("clothe_tags", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Clothe.PhotoClothes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClotheId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ColorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsMain");

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClotheId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ClotheId", "ColorId")
                        .IsUnique()
                        .HasFilter("\"IsMain\" = true");

                    b.ToTable("photo_clothes", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Stock.ClothesStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClotheId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.Property<Guid>("SizeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("SizeId");

                    b.HasIndex("ClotheId", "SizeId", "ColorId")
                        .IsUnique();

                    b.ToTable("clothes_stock", null, t =>
                        {
                            t.HasCheckConstraint("ck_clothes_stock_quantity_valid", "\"quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Stock.StockNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsNotified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("StockId", "UserEmail")
                        .IsUnique();

                    b.ToTable("stock_notifications", (string)null);
                });

            modelBuilder.Entity("Clothy.Shared.Events.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Clothe.ClotheItem", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.Catalog.Brand", "Brand")
                        .WithMany("ClotheItems")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Catalog.ClothingType", "ClothyType")
                        .WithMany("Items")
                        .HasForeignKey("ClothingTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Catalog.Collection", "Collection")
                        .WithMany("ClotheItems")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Brand");

                    b.Navigation("ClothyType");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Clothe.ClotheMaterial", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.Clothe.ClotheItem", "Clothe")
                        .WithMany("ClotheMaterials")
                        .HasForeignKey("ClotheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Catalog.Material", "Material")
                        .WithMany("ClotheMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothe");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Clothe.ClothePopularity", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.Clothe.ClotheItem", "ClotheItem")
                        .WithMany("ClothePopularities")
                        .HasForeignKey("ClotheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClotheItem");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Clothe.ClotheTag", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.Clothe.ClotheItem", "Clothe")
                        .WithMany("ClotheTags")
                        .HasForeignKey("ClotheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Catalog.Tag", "Tag")
                        .WithMany("ClotheTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Clothe.PhotoClothes", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.Clothe.ClotheItem", "Clothe")
                        .WithMany("Photos")
                        .HasForeignKey("ClotheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Catalog.Color", "Color")
                        .WithMany("PhotoClothes")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Clothe");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Stock.ClothesStock", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.Clothe.ClotheItem", "Clothe")
                        .WithMany("Stocks")
                        .HasForeignKey("ClotheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Catalog.Color", "Color")
                        .WithMany("ClothesStocks")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Catalog.Size", "Size")
                        .WithMany("ClothesStocks")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothe");

                    b.Navigation("Color");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Stock.StockNotification", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.Stock.ClothesStock", "Stock")
                        .WithMany("StockNotifications")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Brand", b =>
                {
                    b.Navigation("ClotheItems");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.ClothingType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Collection", b =>
                {
                    b.Navigation("ClotheItems");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Color", b =>
                {
                    b.Navigation("ClothesStocks");

                    b.Navigation("PhotoClothes");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Material", b =>
                {
                    b.Navigation("ClotheMaterials");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Size", b =>
                {
                    b.Navigation("ClothesStocks");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Catalog.Tag", b =>
                {
                    b.Navigation("ClotheTags");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Clothe.ClotheItem", b =>
                {
                    b.Navigation("ClotheMaterials");

                    b.Navigation("ClothePopularities");

                    b.Navigation("ClotheTags");

                    b.Navigation("Photos");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Stock.ClothesStock", b =>
                {
                    b.Navigation("StockNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
