// <auto-generated />
using System;
using Clothy.CatalogService.DAL.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clothy.CatalogService.DAL.Migrations
{
    [DbContext(typeof(ClothyCatalogDbContext))]
    partial class ClothyCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.ClotheItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClothingTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MainPhotoURL")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ClothingTypeId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("clothe_items", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.ClotheMaterial", b =>
                {
                    b.Property<Guid>("ClotheId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer")
                        .HasColumnName("percentage");

                    b.HasKey("ClotheId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("clothe_materials", null, t =>
                        {
                            t.HasCheckConstraint("ck_clothe_materials_percetage_valid", "\"percentage\" >= 0 AND \"percentage\" <= 100");
                        });
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.ClotheTag", b =>
                {
                    b.Property<Guid>("ClotheId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ClotheId", "TagId");

                    b.HasIndex("ClotheId");

                    b.HasIndex("TagId");

                    b.ToTable("clothe_tags", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.ClothesStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClotheId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.Property<Guid>("SizeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("SizeId");

                    b.HasIndex("ClotheId", "SizeId", "ColorId")
                        .IsUnique();

                    b.ToTable("clothes_stock", null, t =>
                        {
                            t.HasCheckConstraint("ck_clothes_stock_quantity_valid", "\"quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.ClothingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ClothingTypes");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("hexcode");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HexCode")
                        .IsUnique();

                    b.ToTable("colors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Color_HexCode", "\"hexcode\" ~ '^#[0-9A-Fa-f]{6}$'");
                        });
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.PhotoClothes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClotheId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClotheId");

                    b.ToTable("photo_clothes", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("sizes", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.ClotheItem", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.Brand", "Brand")
                        .WithMany("ClotheItems")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Clothy.CatalogService.Domain.Entities.ClothingType", "ClothyType")
                        .WithMany("Items")
                        .HasForeignKey("ClothingTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Collection", "Collection")
                        .WithMany("ClotheItems")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Brand");

                    b.Navigation("ClothyType");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.ClotheMaterial", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.ClotheItem", "Clothe")
                        .WithMany("ClotheMaterials")
                        .HasForeignKey("ClotheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Material", "Material")
                        .WithMany("ClotheMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothe");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.ClotheTag", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.ClotheItem", "Clothe")
                        .WithMany("ClotheTags")
                        .HasForeignKey("ClotheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Tag", "Tag")
                        .WithMany("ClotheTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.ClothesStock", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.ClotheItem", "Clothe")
                        .WithMany("Stocks")
                        .HasForeignKey("ClotheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Color", "Color")
                        .WithMany("ClothesStocks")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothy.CatalogService.Domain.Entities.Size", "Size")
                        .WithMany("ClothesStocks")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothe");

                    b.Navigation("Color");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.PhotoClothes", b =>
                {
                    b.HasOne("Clothy.CatalogService.Domain.Entities.ClotheItem", "Clothe")
                        .WithMany("Photos")
                        .HasForeignKey("ClotheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothe");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Brand", b =>
                {
                    b.Navigation("ClotheItems");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.ClotheItem", b =>
                {
                    b.Navigation("ClotheMaterials");

                    b.Navigation("ClotheTags");

                    b.Navigation("Photos");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.ClothingType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Collection", b =>
                {
                    b.Navigation("ClotheItems");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Color", b =>
                {
                    b.Navigation("ClothesStocks");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Material", b =>
                {
                    b.Navigation("ClotheMaterials");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Size", b =>
                {
                    b.Navigation("ClothesStocks");
                });

            modelBuilder.Entity("Clothy.CatalogService.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ClotheTags");
                });
#pragma warning restore 612, 618
        }
    }
}
